# Generated by Django 5.1.1 on 2024-09-23 12:38

import django.utils.timezone
import uuid
from django.db import migrations, models


def generate_uuids(apps, schema_editor):
    # Get the model we're updating
    CustomUser = apps.get_model('users', 'CustomUser')
    
    # Loop through existing records that don't have a UUID
    for user in CustomUser.objects.all():
        if not user.id:
            user.id = uuid.uuid4()  # Generate UUID for existing records
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_created_by_alter_customuser_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        # Add the data migration to generate UUIDs for existing records
        migrations.RunPython(generate_uuids),
    ]
