# Generated by Django 5.1.1 on 2024-09-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_date_created_customuser_last_modified_and_more'),
    ]

    operations = [
    ]
