# Generated by Django 5.1.1 on 2024-10-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_uid_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
