# Generated by Django 5.1.1 on 2024-10-04 05:03

import core.utils
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('batch_code', models.CharField(default=core.utils.generate_batch_code, editable=False, max_length=6, unique=True)),
                ('validation_type', models.CharField(choices=[('Single', 'Single'), ('Bulk', 'Bulk')], default='Single', max_length=10)),
                ('approval_comments', models.TextField(blank=True, null=True)),
                ('aproval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('total_approved', models.PositiveIntegerField(default=0)),
                ('total_rejected', models.PositiveIntegerField(default=0)),
                ('total_record', models.PositiveIntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_batches', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('customer_full_name', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=50)),
                ('meter_no', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('nearest_landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('setup_date', models.DateField(default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('cin', models.CharField(blank=True, max_length=50, null=True)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status_code', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Closed', 'Closed'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('account_type', models.CharField(choices=[('Postpaid', 'Postpaid'), ('Prepaid', 'Prepaid')], default='Prepaid', max_length=10)),
                ('current_tariff_code', models.CharField(blank=True, choices=[('R1', 'R1'), ('R2', 'R2'), ('R3', 'R3'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('S1', 'S1')], max_length=2, null=True)),
                ('correct_tariff_code', models.CharField(blank=True, choices=[('R1', 'R1'), ('R2', 'R2'), ('R3', 'R3'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('S1', 'S1')], max_length=2, null=True)),
                ('tariff_class', models.CharField(blank=True, choices=[('LFN', 'LFN'), ('NMD', 'NMD'), ('MD1', 'MD1'), ('MD2', 'MD2'), ('MD3', 'MD3')], max_length=3, null=True)),
                ('feeder', models.CharField(blank=True, max_length=255, null=True)),
                ('feeder_id', models.CharField(blank=True, max_length=50, null=True)),
                ('service_center', models.CharField(blank=True, max_length=255, null=True)),
                ('distribution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dss_id', models.CharField(blank=True, max_length=50, null=True)),
                ('lt_pole_id', models.CharField(blank=True, max_length=50, null=True)),
                ('service_wire', models.CharField(blank=True, max_length=255, null=True)),
                ('upriser', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('business_hub', models.CharField(blank=True, max_length=255, null=True)),
                ('account_category', models.CharField(choices=[('Resident', 'Resident'), ('Commercial', 'Commercial'), ('Others', 'Others')], max_length=10)),
                ('connection_type', models.CharField(choices=[('Metered', 'Metered'), ('Un-Metered', 'Un-Metered')], max_length=10)),
                ('cust_nature_of_business', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_nin', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_supply_type', models.CharField(choices=[('1-Phase', '1-Phase'), ('3-Phase', '3-Phase')], max_length=10)),
                ('customer_estimated_load', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cust_has_meter', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('customer_meter_category', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_meter_manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_meter_saled', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('customer_meter_accessible', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('customer_meter_location', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], default='Outdoor', max_length=10)),
                ('customer_bill_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_has_account_no', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('customer_group', models.CharField(choices=[('New', 'New'), ('Potential', 'Potential'), ('Existing', 'Existing')], default='New', max_length=10)),
                ('is_landlord', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('landlord_name', models.CharField(blank=True, max_length=255, null=True)),
                ('landlord_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('tenant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('meter_ct_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customer.customerbatch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
