# Generated by Django 5.1.1 on 2024-10-11 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbatch',
            name='approval_comments',
        ),
        migrations.RemoveField(
            model_name='customerbatch',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='customerbatch',
            name='aproval_status',
        ),
        migrations.RemoveField(
            model_name='customerbatch',
            name='date_approved',
        ),
        migrations.AddField(
            model_name='customer',
            name='approval_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='aproval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_no',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='data_entry_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='customerbatch',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerbatch',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
