# Generated by Django 5.1.1 on 2024-10-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customerbatch_approval_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbatch',
            name='slug',
        ),
        migrations.AlterField(
            model_name='customer',
            name='cin',
            field=models.CharField(default=12349384, max_length=50),
            preserve_default=False,
        ),
    ]
