# Generated by Django 5.1.1 on 2024-10-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_customerbatch_slug_alter_customer_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_no',
            field=models.CharField(editable=False, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customerbatch',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
