# Generated by Django 5.1.1 on 2024-10-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_customer_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbatch',
            name='upload_histories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
