# Generated by Django 5.1.1 on 2024-10-19 21:55

import customer.utils
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customerbatch_upload_histories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='application_date',
            field=customer.utils.CustomDateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='connection_type',
            field=models.CharField(choices=[('Metered', 'Metered'), ('Un-Metered', 'Un-Metered'), ('Unmetered', 'Unmetered')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='setup_date',
            field=customer.utils.CustomDateField(),
        ),
    ]
